name: Publish

on:
  repository_dispatch:
    types: publish

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Get tag number
        id: get_tag
        run: echo ::set-output name=TAG::$(echo "$GITHUB_REF" | cut -d / -f 3)
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4 # zizmor: ignore[artipacked]
        with:
          persist-credentials: true
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - name: Cache node modules
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - run: yarn install
      - run: git config --local user.email "action@github.com"
      - run: git config --local user.name "GitHub Action"
      #- run: yarn config set version-sign-git-tag true
      - run: |
              if [[ "$VERSION" == *"-"* ]]; then
                  yarn publish --new-version "$VERSION" --tag=beta
              else
                  yarn publish --new-version "$VERSION"
              fi
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          VERSION: ${{ github.event.inputs.version }}
      - run: git push
